export const START = '_START';
export const FAIL = '_FAIL';
export const SUCCESS = '_SUCCESS';

export const LOAD_MOVIE_DETAILS = 'LOAD_MOVIE_DETAILS';

export const LOAD_SIMILAR_MOVIES = 'LOAD_SIMILAR_MOVIES';

export const LOAD_POPULAR_MOVIES = 'LOAD_POPULAR_MOVIES';

export const SEARCH_MOVIE = 'SEARCH_MOVIE';

export const ADD_FAVORITE_MOVIE = 'ADD_FAVORITE_MOVIE';